### ISSUE TITLE
Javascript error while displaying diff

### ISSUE THREAD

**Issue by ltozi** [jenkinsci/last-changes-plugin#12]
Hi @rmpestano,

I found a problem (I use svn) in browser console while showing diff involving **binary** files. I realized this because a cli attempt of svn diff didn't display my xml file, even if modified. (See attachment)

There's an svn option (--force) to treat files in text mode but I thinks this could cause rendering problem in case bigger binary archives like jar are added/removed. 

What do you suggest?

Thanks in advance

![typeerror this each is not a function](https://user-images.githubusercontent.com/10612162/32095391-4ac366d4-bb03-11e7-8abb-ccec4eae81cd.png)

**Comment by ltozi** [comment]
Tried with xml in textual diff mode but the same problem occurs. Now I see the xml diff, but the another modified file is missing.

**Comment by rmpestano** [comment]
Hi @ltozi,

I've tried to reproduce your error by changing a Jenkinsfile in a svn repo and it is working fine here:

![diff](https://user-images.githubusercontent.com/1592273/32103175-01dcd554-bafe-11e7-9979-8f77033d1b17.png)


Also see the generated diff (just look into html page source):

```
 var buildChanges = "Index: Jenkinsfile\n===================================================================\n--- Jenkinsfile\t(revision 2953)\n+++ Jenkinsfile\t(revision 2954)\n@@ -54,6 +54,7 @@\n                         dir(\'ft-tests\') {\n                             unstash \'src\'\n                             sh \'mvn package -Pft-tests -Pwebdriver-phantomjs -Darquillian.port-offset=120  -Darquillian.management-port=10110 -Dmaven.javadoc.skip=true\'\n+                            livingDocs(featuresDir: \'target\') \n                             stash includes: \'src\/**, pom.xml, target\/**\', excludes: \'target\/server\/**\', name: \'ft\'\n                         }\n                     }\n@@ -74,18 +75,9 @@\n             }\n         }\n \n-        stage(\"Living docs\") {\n-         steps {\n-            dir(\"docs\") {\n-                    unstash \'ft\' \/\/loads \'ft\' folder because bdd tests are executed in \'ft\' stage \n-                    livingDocs(featuresDir: \'target\') \n-                }\n-            }\n-        }\n-\n         stage(\"Quality Gate\") {\n             steps {\n-                sh \'sleep 5\'\n+                sh \'sleep 10\'\n                 timeout(time: 5, unit: \'MINUTES\') {\n                     script {\n                         def result = waitForQualityGate()  \n@@ -103,6 +95,7 @@\n             stage(\'docs\') {\n                 steps {\n                     dir(\'docs\') {\n+                        unstash \'src\'\n                         sh \'package -Pdocs -Dapm.url=https:\/\/secweb.intra.rs.gov.br\/apm-arq4 -Dmaven.javadoc.skip=true\'\n                         stash includes: \'src\/**, pom.xml, target\/**\', name: \'docs\'\n \n@@ -113,13 +106,10 @@\n \n             stage(\'Deploy des\') {\n                 steps {\n-                    sh \'PRMavenPlugin:deploy-proconsole -Dgrupo=apm -Dobservacao=\"deploy para desenvolvimento via pipeline\" -Dservidor=\"jboss7.des.intra.rs.gov.br\" -Dmaven.javadoc.skip=true\'\n-                }\n-            }\n-\n-            stage(\'Deploy des\') {\n-                steps {\n-                    sh \'PRMavenPlugin:deploy-proconsole -Dgrupo=apm -Dobservacao=\"deploy para desenvolvimento via pipeline\" -Dservidor=\"jboss7.des.intra.rs.gov.br\" -Dmaven.javadoc.skip=true\'\n+                    dir(\'deploy-des\') {\n+                        unstash \'docs\'\n+                        sh \'PRMavenPlugin:deploy-proconsole -Dgrupo=apm -Dobservacao=\"deploy para desenvolvimento via pipeline\" -Dservidor=\"jboss7.des.intra.rs.gov.br\" -Dmaven.javadoc.skip=true\'\n+                    }\n                 }\n             }\n \n@@ -141,9 +131,6 @@\n                 }\n             }\n \n-        }\n-\n-\n \n     } \/\/end stages\n \n@@ -154,9 +141,7 @@\n \n         changed {\n             notifyStatusChangeViaEmail(currentBuild.currentResult)\n-        }\n-\n-        \n+        } \n     }\n \n }\n";
```  

Can you share the generated diff for your build?

**Comment by rmpestano** [comment]
I've also tested renaming the file as you did but also works for me:

![diff-rename](https://user-images.githubusercontent.com/1592273/32103649-1fb6be58-bb00-11e7-9e18-dfb4cccdc17f.png)


here is the svn version that our jenkins is using:

``` 
+ svn --version
svn, version 1.7.14 (r1542130)
   compiled Aug 13 2015, 06:13:02

Copyright (C) 2013 The Apache Software Foundation.
This software consists of contributions made by many people; see the NOTICE
file for more information.
Subversion is open source software, see http://subversion.apache.org/

The following repository access (RA) modules are available:

* ra_neon : Module for accessing a repository via WebDAV protocol using Neon.
  - handles 'http' scheme
  - handles 'https' scheme
* ra_svn : Module for accessing a repository using the svn network protocol.
  - with Cyrus SASL authentication
  - handles 'svn' scheme
* ra_local : Module for accessing a repository on local disk.
  - handles 'file' scheme
```

**Comment by ltozi** [comment]
Well. I cannot reproduce the problem. Sometimes it works perfectly, sometimes not. I'm actually using multibranch pipeline that seems to have some problems, like double workspace checkout (one for Jenkinsfile and one for the created job)

This is, for example, a piece of console log where you can see an update but null problem occurs:

> U         gestoreDB-server/build.properties
> At revision 586875
> 
> Using sole credentials deploy/****** in realm ‘<https://td-demetra-01.ubiquity.eu:443> Password Prompt’
> [Pipeline] lastChanges
> Publishing build last changes...
> Last changes from revision **null** to **null** published successfully!

**Comment by ltozi** [comment]
This is another case causing a blank page diff:

Publishing build last changes...
Last changes from revision null to 586888 published successfully! 


P.S: I forget. My SVN version is 1.8

**Comment by ltozi** [comment]
Anyway, the javascript TypeError in console is always encountered.

**Comment by rmpestano** [comment]
> Anyway, the javascript TypeError in console is always encountered.

Yes, same thing here but I don't think it is the cause of your problem. I think, as you mentioned, it is related to multibranch pipeline or maybe the version of svn.
