### ISSUE TITLE
Group changes per commit for a single build

### ISSUE THREAD

**Issue by ltozi** [jenkinsci/last-changes-plugin#13]
Hi @rmpestano,

it is very common to have multiple commit in a single build, so I think it could be useful to have changes grouped by revision involved in a single build. Something like a "relative" changelog containing revision range diff.

What do you think?

**Comment by rmpestano** [comment]
Hi @ltozi,

Although it is not what you proposed in this issue, I've just released a new version of the plugin (1.0.12) which supports diff against **last successful build**:

```
 post {
            always {
                lastChanges lastSuccessfulBuild: true format:'SIDE',matching: 'LINE'
            }
}
```

**Comment by ltozi** [comment]
You're right.

Saving previous build release could do the trick, even if my initial
intent using this plugin was to have a better visualization of jenkins
changelog.




Il Ven 27 Ott 2017, 19:16 Rafael M. Pestano <notifications@github.com> ha
scritto:

**Comment by rmpestano** [comment]
About change logs, have you look at [Git changelog plugin](https://wiki.jenkins.io/display/JENKINS/Git+Changelog+Plugin)?

**Comment by ltozi** [comment]
Cool, but we have plain old svn under the hood, and probably we have to
install something like WebSvn.

Thanks anyway!

Il Dom 29 Ott 2017, 13:26 Rafael M. Pestano <notifications@github.com> ha
scritto:

**Comment by rmpestano** [comment]
Related to #33
