### ISSUE TITLE
Plugin creates repo clone for each build.

### ISSUE THREAD

**Issue by sflynn-dell** [jenkinsci/last-changes-plugin#29]
Hi,
  We are using a git repo.  Is it expected behavior if the plugin cannot find ../<workspace>/.git, that it will create a clone for the build in that builds folder on the master node?

  I confirmed that the workspace does contain a .git folder, and that git commands run from the workspace succeed; git sees this workspace as a  git repository.

  Our job uses a custom workspace, and we specify a reference repository in the Advanced clone behaviors.

Thanks,

Steve F.

**Comment by rmpestano** [comment]
Hi Steve, 

Can I reproduce the issue with this repo? If yes can you guide me on how to do such configuration?

Thanks for reporting!

**Comment by sflynn-dell** [comment]
In trying to construct a test case that could reproduce this, I noticed that every build gets a .git which is in effect a bare repository.  In our case this means a folder taking up 3.2G of space, per build.  We are unable to use your plugin, for now.

I am only curious as to why this is done, when the workspace itself contains a .git folder, and as you say in the readme, this folder is necessary for the plugin to work.

**Comment by rmpestano** [comment]
The .git folder needs to be copied from workspace to where the build runs so it can be run on slaves nodes.


Note that It is not "mine" but "ours" ;)

**Comment by sflynn-dell** [comment]
I guess I could have used 'this'. 

I cannot make sense of the logic in copying the .git folder to the master, when the slave node is where the build is running, and where the original .git folder resides.  Is there a limitation of carrying out these operations on the slave inside the workspace itself?

**Comment by sflynn-dell** [comment]
What about an option to clean up the repo on the master after the patch file is created?

**Comment by rmpestano** [comment]
> What about an option to clean up the repo on the master after the patch file is created?
sure, can you try with following SNAPSHOT? 

[last-changes-2.2-SNAPSHOT.zip](https://github.com/jenkinsci/last-changes-plugin/files/1463688/last-changes-2.2-SNAPSHOT.zip)

You'll need to rename it from `.zip` to `.hpi` before installing into your Jenkins.

> I cannot make sense of the logic in copying the .git folder to the master, when the slave node is where the build is running

The problem is that the plugin needs to publish its results to master in order to create menu on the left panel which links to the diff page, it has other problems which involves remote file copying, believe me  it's easier to work always on master.

Note that we only copy the .git folder contents and it is quite surprising that it has 3.2 GB but with the version above the plugin should delete it.

**Comment by sflynn-dell** [comment]
Thank you.  I will test it as soon as I am able and report back.

**Comment by sflynn-dell** [comment]
The .git folder remains.

**Comment by sflynn-dell** [comment]
The .git on the remote is being removed.

**Comment by rmpestano** [comment]
Hi @sflynn-dell, you're right, please try with version below:

 
[last-changes-2.2-SNAPSHOT.zip](https://github.com/jenkinsci/last-changes-plugin/files/1478221/last-changes-2.2-SNAPSHOT.zip)

**Comment by rmpestano** [comment]
The fix is available in v2.2, any problem you find related to this just reopen this issue. Thanks for your feedback.
