### ISSUE TITLE
Diff with an specific revision

### ISSUE THREAD

**Issue by rmpestano** [jenkinsci/last-changes-plugin#3]
Currently the plugin always compare and create the diff with current and previous revisions. Add the ability to specify an specific revision as parameter. This revision will be diff'ed with current checked out/cloned revision.

**Comment by klavan** [comment]
Hi,

Can we provide end revision value through variable ?

It doesnt seem to work that way when i tried

I've saved revision number in old_id and provided ${old_id} as input to end revision.
but it didn't work

could you please help.

**Comment by rmpestano** [comment]
Hi,

how did you saved old_id? 

can you see its value when you print it in a shell script before build?

e.g echo ${old_id}

**Comment by klavan** [comment]
Yes am able to print old_id

+ old_id=ce869cd6bceafba504dc9ad9010e6b117066b1be
+ echo ce869cd6bceafba504dc9ad9010e6b117066b1be

in execute shell
