### ISSUE TITLE
findVCSDir researches only one, first folder from workspace.

### ISSUE THREAD

**Issue by MarekZa** [jenkinsci/last-changes-plugin#33]
Function, a module for searching SVn or GIT local copy only do it in a first founded folder in a workspace. If you have more than one folder, e.g for reports it is possible that this module checks only if a local copy exists in this folder and if not found, raise an error "Git or Svn directories not found in workspace..."
-workspace
----dir1 <- module only search inside this directory
--------dir1/A
--------dir1/B
----dir2<- module do not check this structure/directory and do not found .svn or .git so do not found local copy
--------dir2/A
--------dir2/.svn
Wery fast patch, but without considering the depth:

	private FilePath findVCSDir(FilePath workspace, String dir) throws IOException, InterruptedException {
		FilePath gitDir = null;
		for (FilePath filePath : workspace.listDirectories()) {
			if (filePath.getName().equalsIgnoreCase(dir)) {
				return filePath;
			} else {
				gitDir = findVCSDirInSubDirectories(filePath, dir);
			}
		}
		return gitDir;
	}

	private FilePath findVCSDirInSubDirectories(FilePath sourceDir, String dir) throws IOException, InterruptedException {
		for (FilePath filePath : sourceDir.listDirectories()) {
			if (filePath.getName().equalsIgnoreCase(dir)) {
				return filePath;
			} else {
				return findVCSDirInSubDirectories(filePath, dir);
			}
		}
		return null;
	}

**Comment by rmpestano** [comment]
Hi @MarekZa, this can only happen on svn right? 

I think we could provide an advanced config in order to provide the vcsDir so the plugin would search vcs dir starting from provided directory. This way we would cover this corner cases. WDYT?

**Comment by rmpestano** [comment]
If I got it right It will not happen for git, [see here](https://stackoverflow.com/questions/436125/two-git-repositories-in-one-directory). 

Lets stick with the vcsDir parameter for your case

**Comment by rmpestano** [comment]
Hi again @MarekZa, can you test the new _vcsDir_ param with attached SNAPSHOT?

you'll need to rename it from **.zip** to **.hpi** before instaling into your Jenkins.

[last-changes.zip](https://github.com/jenkinsci/last-changes-plugin/files/1537416/last-changes.zip)

**Comment by rmpestano** [comment]
Fixed in version 2.3
