### ISSUE TITLE
Makes LastChanges available in pipeline script

### ISSUE THREAD

**Issue by redbrain** [jenkinsci/last-changes-plugin#37]
Hi looking in the code for the plugin i notice:

LastChangesBuildAction::public LastChanges getBuildChanges()

Is it possible to access this member function in a the pipeline script like:

```
def commits = step([$class: 'LastChanges', since:'LAST_SUCCESSFUL']).getBuildChanges():

for i in commits:
    print i.getMessage()
```

Would be really useful to have this.

**Comment by rmpestano** [comment]
Hi @redbrain,

do you know other plugins that expose a pipeline dsl and provide such access so we can take as example? 

 Just exposing this [local variable](https://github.com/jenkinsci/last-changes-plugin/blob/29a8526c97695d8a7204f80ee728b95b30e99975/src/main/java/com/github/jenkins/lastchanges/LastChangesPublisher.java#L244) as an instance variable would do the trick?

**Comment by rmpestano** [comment]
👍
