### ISSUE TITLE
Pipeline: plugin does not find SCMs

### ISSUE THREAD

**Issue by thomas-oo** [jenkinsci/last-changes-plugin#4]
Pipeline job def:
```
node() {
  def STOP_ON_ERROR = '';
  def mvnHome
  def javaHome
  def failed = false;
  try{
    stage('Preparation') { // for display purposes
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.
      checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/thomas-oo/eventAppFrontend']]])
    }
  }catch(Exception e){
    failed = true
    echo 'Build failed'
  }finally{
    if(!failed){
      stage('Last Changes'){
        echo 'In last changes'
        step([$class: 'LastChangesPublisher', format: 'LINE', matchWordsThreshold: '0.25', matching: 'NONE', matchingMaxComparisons: '1000', showFiles: true, synchronisedScroll: true, endRevision: ''])
      }
    }
    echo 'In finally block'
  }
}
```

The pipeline job runs correct and goes into the Last Changes stage Then throws an error, java.lang.RuntimeException: Git/Svn must be configured on your job to publish Last Changes.

When debugging this plugin, looks like in LastChangesPublisher, wkfJob.getSCMs() returns an empty collection and does not go into the for loop after.

Is there something I need to config in my pipeline script so jenkins knows this is a git scm?

**Comment by rmpestano** [comment]
Hi @thomas-oo,

I see the error and found the cause. Just to confirm with you, the second time you run the job the last changes are published, right?

**Comment by thomas-oo** [comment]
I've actually changed the script a little bit now, in the finally block I clear the workspace. Now, on the second run, it still does not publish. I'm trying to debug this issue as well. wkfJobs.getSCMs again, returns 0 for me.

However, there was one case where it returned a collection with one SCM in it.. unfortunately I'm not sure how to replicate it.

I'm going to look into this as well

**Comment by rmpestano** [comment]
I see, for me your script worked when I run the job a second time but anyway I think I found a solution, I'm testing it

**Comment by rmpestano** [comment]
Well I got the same behaviour with the other solution, still doesn't work for the first time. I've commited the other approach because its clean but We still need to figure out how to get scm in a pipeline workflow.

**Comment by thomas-oo** [comment]
Can confirm, after the second run, the reports are generated. For my use case, this is enough to say it works (we really use the plugin to see the last changes from build to build). Thank you!

**Comment by rmpestano** [comment]
Hi @thomas-oo, glad it works for you. Just FYI I've opened an issue at Jenkins [Jira here ](https://issues.jenkins-ci.org/browse/JENKINS-45720) to hear from experts the best approach.
