### ISSUE TITLE
Support for variables in end revision input

### ISSUE THREAD

**Issue by rmpestano** [jenkinsci/last-changes-plugin#5]
We should be able to pass a variable to end revision input, currently the following error is throw:

```
ERROR: Last Changes NOT published due to the following error: For input string: "${REV}"
```

**Comment by rmpestano** [comment]
Hi @klavan,

can you test with the version below? you need to rename from .zip to .hpi

[last-changes.zip](https://github.com/jenkinsci/last-changes-plugin/files/1214939/last-changes.zip)

**Comment by klavan** [comment]
Hi @rmpestano,

Thanks for the response.
I still see the same error with the latest zip file you have provided.

Could you please help.

**Comment by rmpestano** [comment]
Can you tell me how are you providing the variable? I've tested here with environment variables: https://stackoverflow.com/questions/30110876/passing-variable-from-shell-script-to-jenkins

**Comment by klavan** [comment]
Thanks alot for the help @rmpestano.
I'm able to use the  variable now through environment variable properties file.

Earlier i didn't store it in environment file and directly used it.
So i've faced the issue.

Its working now !!

**Comment by rmpestano** [comment]
Great! I'll release a version with this fix today, thank you for the feedback :+1:

**Comment by klavan** [comment]
Hi @rmpestano,

I've found one more issue with providing environment variable in end_revision field.
It replaces environment variable after 1st run and it uses that constant value for further runs.

Can you please try this scenario ?

**Comment by rmpestano** [comment]
Yes, thats a bug, I've created #6 to handle it. Thanks for reporting.
