### ISSUE TITLE
EndRevision input is replaced when using Environment Variables

### ISSUE THREAD

**Issue by rmpestano** [jenkinsci/last-changes-plugin#6]
As reported in https://github.com/jenkinsci/last-changes-plugin/issues/5#issuecomment-321750393
the environment variable is replaced by its value after first run.

**Comment by rmpestano** [comment]
Hi @klavan ,

can you try with the version below?

[last-changes.zip](https://github.com/jenkinsci/last-changes-plugin/files/1217784/last-changes.zip)


OBS: Don't forget to rename the zip to .hpi before instaling it.

**Comment by klavan** [comment]
This version seems to be working fine.
I've tested it in my environment.
Thanks a lot !!!

**Comment by rmpestano** [comment]
version 1.0.9 should be available soon with this fix.
