### ISSUE TITLE
Last Changes Plugin seems to slow performance of viewing Multi-Branch Pipeline Build Page

### ISSUE THREAD

**Issue by adam-krieg** [jenkinsci/last-changes-plugin#70]
I'm running into serious performance issues with the Jenkins UI (not build jobs), where it takes many seconds to show our main build page for our Multi-Branch Pipeline page.  Looking into things with the Jenkins Performance Monitor, I see that often the Last Changes plugin appears in the stack trace of the slow thread.  I'm confused because the Last Changes Plugin shouldn't need to be invoked for this page since it won't provide any content for that page, only for particular builds.  Is there a way to not have the Last Changes plugin invoke on the main page for a Multi-Branch Pipeline?

Handling GET /job/MainPage/ from 29.3.171.144 : qtp2007328737-337912 View/index.jelly ItemColumn/column.jelly
sun.nio.ch.NativeThread.current(Native Method)
sun.nio.ch.NativeThreadSet.add(NativeThreadSet.java:46)
sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:306)
sun.nio.ch.ChannelInputStream.available(ChannelInputStream.java:116)
java.io.BufferedInputStream.available(BufferedInputStream.java:410)
java.io.FilterInputStream.available(FilterInputStream.java:168)
java.io.PushbackInputStream.available(PushbackInputStream.java:277)
sun.nio.cs.StreamDecoder.inReady(StreamDecoder.java:363)
sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:324)
sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
java.io.InputStreamReader.read(InputStreamReader.java:184)
com.thoughtworks.xstream.core.util.XmlHeaderAwareReader.read(XmlHeaderAwareReader.java:223)
org.kxml2.io.KXmlParser.peek(Unknown Source)
org.kxml2.io.KXmlParser.pushText(Unknown Source)
org.kxml2.io.KXmlParser.nextImpl(Unknown Source)
org.kxml2.io.KXmlParser.next(Unknown Source)
com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109)
com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:135)
com.thoughtworks.xstream.io.xml.AbstractPullReader.getValue(AbstractPullReader.java:180)
com.thoughtworks.xstream.io.ReaderWrapper.getValue(ReaderWrapper.java:48)
com.thoughtworks.xstream.converters.SingleValueConverterWrapper.unmarshal(SingleValueConverterWrapper.java:49)
com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:391)
hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:329)
hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:268)
com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:391)
hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:329)
hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:268)
com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:71)
hudson.util.RobustCollectionConverter.populateCollection(RobustCollectionConverter.java:85)
com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:80)
hudson.util.RobustCollectionConverter.unmarshal(RobustCollectionConverter.java:76)
com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:391)
hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:329)
hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:268)
com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1189)
hudson.util.XStream2.unmarshal(XStream2.java:161)
hudson.util.XStream2.unmarshal(XStream2.java:132)
com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1173)
hudson.XmlFile.unmarshal(XmlFile.java:178)
hudson.XmlFile.unmarshal(XmlFile.java:161)
org.jenkinsci.plugins.workflow.job.WorkflowRun.reload(WorkflowRun.java:507)
hudson.model.Run.<init>(Run.java:333)
org.jenkinsci.plugins.workflow.job.WorkflowRun.<init>(WorkflowRun.java:242)
sun.reflect.GeneratedConstructorAccessor814.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:422)
jenkins.model.lazy.LazyBuildMixIn.loadBuild(LazyBuildMixIn.java:166)
jenkins.model.lazy.LazyBuildMixIn$1.create(LazyBuildMixIn.java:143)
hudson.model.RunMap.retrieve(RunMap.java:224)
hudson.model.RunMap.retrieve(RunMap.java:57)
jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:501)
jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:483)
jenkins.model.lazy.AbstractLazyLoadRunMap.getByNumber(AbstractLazyLoadRunMap.java:381)
jenkins.model.lazy.AbstractLazyLoadRunMap.search(AbstractLazyLoadRunMap.java:346)
jenkins.model.lazy.LazyLoadRunMapEntrySet$1.next(LazyLoadRunMapEntrySet.java:74)
jenkins.model.lazy.LazyLoadRunMapEntrySet$1.next(LazyLoadRunMapEntrySet.java:63)
java.util.AbstractMap$2$1.next(AbstractMap.java:396)
com.github.jenkins.lastchanges.LastChangesProjectAction$LastChangesActionFactory.createFor(LastChangesProjectAction.java:54)
com.github.jenkins.lastchanges.LastChangesProjectAction$LastChangesActionFactory.createFor(LastChangesProjectAction.java:45)
hudson.model.Actionable.createFor(Actionable.java:114)
hudson.model.Actionable.getAction(Actionable.java:337)
jenkins.branch.ItemColumn.isPrimary(ItemColumn.java:68)
sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:497)
org.apache.commons.jexl.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:258)
org.apache.commons.jexl.parser.ASTMethod.execute(ASTMethod.java:104)
org.apache.commons.jexl.parser.ASTReference.execute(ASTReference.java:83)
org.apache.commons.jexl.parser.ASTReference.value(ASTReference.java:57)
org.apache.commons.jexl.parser.ASTReferenceExpression.value(ASTReferenceExpression.java:51)
org.apache.commons.jexl.ExpressionImpl.evaluate(ExpressionImpl.java:80)
hudson.ExpressionFactory2$JexlExpression.evaluate(ExpressionFactory2.java:74)
org.apache.commons.jelly.expression.ExpressionSupport.evaluateRecurse(ExpressionSupport.java:61)
org.apache.commons.jelly.expression.ExpressionSupport.evaluateAsBoolean(ExpressionSupport.java:71)
org.apache.commons.jelly.tags.core.WhenTag.doTag(WhenTag.java:44)
org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.apache.commons.jelly.TagSupport.invokeBody(TagSupport.java:161)
org.apache.commons.jelly.tags.core.ChooseTag.doTag(ChooseTag.java:38)
org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:99)
org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
org.kohsuke.stapler.jelly.JellyViewScript.run(JellyViewScript.java:95)
org.kohsuke.stapler.jelly.IncludeTag.doTag(IncludeTag.java:147)
org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
org.apache.commons.jelly.TagSupport.invokeBody(TagSupport.java:161)
org.apache.commons.jelly.tags.core.ForEachTag.doTag(ForEachTag.java:150)
org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:99)
org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:120)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.apache.commons.jelly.TagSupport.invokeBody(TagSupport.java:161)
org.apache.commons.jelly.tags.core.ForEachTag.doTag(ForEachTag.java:150)
org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:99)
org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:99)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.apache.commons.jelly.tags.core.CoreTagLibrary$1.run(CoreTagLibrary.java:98)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:99)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:120)
org.kohsuke.stapler.jelly.groovy.JellyBuilder.doInvokeMethod(JellyBuilder.java:276)
org.kohsuke.stapler.jelly.groovy.Namespace$ProxyImpl.invoke(Namespace.java:92)
com.sun.proxy.$Proxy74.projectView(Unknown Source)
lib.JenkinsTagLib$projectView$1.call(Unknown Source)
org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
hudson.model.View.main.run(main.groovy:16)
org.kohsuke.stapler.jelly.groovy.GroovierJellyScript.run(GroovierJellyScript.java:74)
org.kohsuke.stapler.jelly.groovy.GroovierJellyScript.run(GroovierJellyScript.java:62)
org.kohsuke.stapler.jelly.IncludeTag.doTag(IncludeTag.java:147)
org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:99)
org.apache.commons.jelly.tags.define.InvokeBodyTag.doTag(InvokeBodyTag.java:91)
org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.apache.commons.jelly.tags.core.CoreTagLibrary$1.run(CoreTagLibrary.java:98)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:120)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:99)
org.apache.commons.jelly.tags.define.InvokeBodyTag.doTag(InvokeBodyTag.java:91)
org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:99)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:99)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:99)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:99)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:99)
org.apache.commons.jelly.tags.define.InvokeBodyTag.doTag(InvokeBodyTag.java:91)
org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:120)
org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:120)
org.kohsuke.stapler.jelly.CompressTag.doTag(CompressTag.java:44)
org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
org.kohsuke.stapler.jelly.JellyViewScript.run(JellyViewScript.java:95)
org.kohsuke.stapler.jelly.DefaultScriptInvoker.invokeScript(DefaultScriptInvoker.java:63)
org.kohsuke.stapler.jelly.DefaultScriptInvoker.invokeScript(DefaultScriptInvoker.java:53)
org.kohsuke.stapler.jelly.ScriptInvoker.execute(ScriptInvoker.java:56)
org.kohsuke.stapler.jelly.ScriptInvoker.execute(ScriptInvoker.java:43)
org.kohsuke.stapler.Facet.handleIndexRequest(Facet.java:282)
org.kohsuke.stapler.jelly.JellyFacet.handleIndexRequest(JellyFacet.java:99)
org.kohsuke.stapler.IndexViewDispatcher.dispatch(IndexViewDispatcher.java:32)
org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:815)
org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:280)
org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
org.kohsuke.stapler.Stapler.invoke(Stapler.java:676)
org.kohsuke.stapler.Stapler.service(Stapler.java:238)
javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:246)
hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:76)
hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:239)
net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)
net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:88)
org.jvnet.hudson.plugins.monitoring.HudsonMonitoringFilter.doFilter(HudsonMonitoringFilter.java:114)
hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)
hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:105)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
org.eclipse.jetty.server.Server.handle(Server.java:505)
org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
java.lang.Thread.run(Thread.java:745)

**Comment by adam-krieg** [comment]
Looks like the LastChangesProjectAction is getting invoked for each branch and each build, which in our case is quite a few builds, but I don't see any output or icons for Last Changes on that page.  Is it necessary to invoke the plugin at the Project level?

**Comment by rmpestano** [comment]
Hi,

[this part of code](https://github.com/jenkinsci/last-changes-plugin/blob/5a38600df75f2748b6afc7feeb5659e35fc2ed27/src/main/java/com/github/jenkins/lastchanges/LastChangesProjectAction.java#L54) has changed due to [JENKINS-50116](https://issues.jenkins-ci.org/browse/JENKINS-50116), I remember @oleg-nenashev has helped me with that.

@oleg-nenashev, any hints on how to mark builds that has published LastChanges without iterating over all builds?

Thanks in advance.

**Comment by adam-krieg** [comment]
That makes sense for single branch projects, but for multi-branch projects, each branch is essentially its own project with its own build history.  It might not make sense to run across all branches and instead only run when the user clicks into a particular branch.

**Comment by rmpestano** [comment]
Alright, I see. I don't have experience with multi-branch projects so any contribution is very welcome

**Comment by adam-krieg** [comment]
Having trouble creating a PR, but I put the following change in and have successfully tested in our local Jenkins:

`package com.github.jenkins.lastchanges;

import com.github.jenkins.lastchanges.model.LastChangesBuild;
import hudson.Extension;
import hudson.model.Action;
import hudson.model.Job;
import hudson.model.ProminentProjectAction;
import hudson.model.Run;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

import jenkins.branch.MultiBranchProject;
import jenkins.model.TransientActionFactory;

public class LastChangesProjectAction extends LastChangesBaseAction implements ProminentProjectAction {

    private final transient Job<?, ?> job;
    private final List<LastChangesBuild> lastChangesBuilds;
    private final String jobName;
    
    public LastChangesProjectAction(Job<?, ?> job, List<LastChangesBuild> lastChangesBuilds) {
        this.job = job;
        this.lastChangesBuilds = lastChangesBuilds;
        this.jobName = job.getName();
    }

    public String job() {
        return jobName;
    }

    public Job<?, ?> getProject() {
        return job;
    }

    @Override
    protected String getTitle() {
        return this.job.getDisplayName();
    }

    public List<LastChangesBuild> getLastChangesBuilds() {
        return lastChangesBuilds;
    }
    
    @Extension
    public static class LastChangesActionFactory extends TransientActionFactory<Job<?, ?>> {

        @Override
        public Collection<? extends Action> createFor(Job<?, ?> j) {
            //Dont' run for multibranch projects
            if (j.getParent() instanceof MultiBranchProject) {
                return Collections.emptyList();
            }
            List<LastChangesBuild> lastChangesBuilds = new ArrayList<>();

            //collects the list of builds that published last changes to show on the last changes history 
            if (j.getBuilds() != null && !j.getBuilds().isEmpty()) {
                for (Run<?, ?> build : j.getBuilds()) {
                    if (build.getAction(LastChangesBuildAction.class) != null) {
                        lastChangesBuilds.add(new LastChangesBuild(build.getNumber(), build.getTime()));
                    }
                }
            }
            if(lastChangesBuilds.isEmpty()) {
                return Collections.emptyList();
            }
            return Collections.singleton(new LastChangesProjectAction(j, lastChangesBuilds));
        }

        @Override
        public Class type() {
            return Job.class;
        }
    }

}
`

**Comment by rmpestano** [comment]
Great, let's do a new release with this fix then! Hopefully I can make a release tomorrow. 

Thank you very much!

**Comment by rmpestano** [comment]
Version 2.7.7 was just released, thank you!
