### ISSUE TITLE
No scroll bar for View Last Changes 

### ISSUE THREAD

**Issue by dpuglielli** [jenkinsci/last-changes-plugin#79]
There is no scroll bar on the View Last Change page even when the quantity of changes would necessitate it. We ae using all the defaults on the Advanced Options configuration. The problem is present on FireFox, Chrome, and Edge Chromium. Obviously changing the html from the commit.jelly template allows for scrolling, but is most likely not the correct change.
from:
             html body {
                 overflow:hidden!important;
             }
to
             html body {
                 overflow:auto!important;
             }

Also, of note is the javascript error written to the console. The prototype.js comes from the base Jenkins installation.
prototype.js:892 Uncaught TypeError: this.each is not a function
    at NamedNodeMap.collect (prototype.js:892)
    at open (diff2html-ui-2.12.2.min.js:1)
    at render (diff2html-ui-2.12.2.min.js:1)
    at HighlightJS.mergeStreams (diff2html-ui-2.12.2.min.js:1)
    at HTMLSpanElement.<anonymous> (diff2html-ui-2.12.2.min.js:1)
    at jquery.min.js:2
    at Function.map (jquery.min.js:2)
    at n.fn.init.map (jquery.min.js:2)
    at HTMLDivElement.<anonymous> (diff2html-ui-2.12.2.min.js:1)
    at jquery.min.js:2

We are using Jenkins 2.245 and v2.7.9 of the last changes plugin.

**Comment by rmpestano** [comment]
Hi @dpuglielli,

So which page are you talking about? commit.jelly is when user is browsing commit details. Why do you think it's wrong overriding the css on the jelly file?  

Maybe we need to change both `index.jelly` and `commit.jelly`. Do you have a print?

> Also, of note is the javascript error written to the console. The prototype.js comes from the base Jenkins installation.

Yes, this js error is there for a long time but seems to not impact the plugin functionality 

Thanks for the feedback!

**Comment by dpuglielli** [comment]
I assumed since the CSS in the commit.jelly file very short and clear, that hiding the scroll bar had to be intentional. I could see vertical scrolling within the line-by-line div. Also, when the html body is changed to 'overflow:auto!important;' the Jenkins breadcrumb div floats with the scroll.

As for which css I modified overrode in the browser, it was the html body css generated from both the commit.jelly and index.jelly templates.

What do you want a print of?

**Comment by intelmatt** [comment]
Any plan to fix this? Also, is there an easy way to work around this in current Jenkins/plugin version?

It's kind of annoying not being able to scroll the "view last changes" page.

thanks

**Comment by rmpestano** [comment]
Hi guys, @dpuglielli can you send a PR with your fix? 

Thanks and sorry for the delay in response

**Comment by ws1088** [comment]
Changing

```
html body {
    overflow:hidden!important;
}
```

to

```
html body {
    overflow:auto!important;
}
```

will cause the breadcrumb to not work probably (got stick in a fixed position while scrolling)

just commenting the line will work:

```
html body {
    #overflow:hidden!important;
}
```

**Comment by rmpestano** [comment]
Hey folks, can you try with following plugin snapshot on your jenkins installation? Just unzip and upload to Jenkins and let me know if the issue is fixed: 
[last-changes.hpi.zip](https://github.com/jenkinsci/last-changes-plugin/files/5260430/last-changes.hpi.zip)

Thanks!

**Comment by intelmatt** [comment]
@rmpestano  Works for me

**Comment by pete312** [comment]
Has this been released? the jenkins plugin manager is showing 2.7.9 is latest and that did not fix it.

**Comment by rmpestano** [comment]
Sorry folks, completely forgot to release. Just released and it should be on plugin center in a few hours.

**Comment by pete312** [comment]
Thanks, That works now.
