### ISSUE TITLE
endRevision does not work

### ISSUE THREAD

**Issue by tsjfd** [jenkinsci/last-changes-plugin#9]
I use the lastChanges-Plugin in a multibranch pipeline script but as soon as I set `endRevision` to anything else than `''` I get an error. I have tried `endRevision: 'master'`, `endRevision: 'origin/master'` etc. It does not work.

Error message: `ERROR: Last Changes NOT published due to the following error: Invalid id: origin/master`

**Comment by rmpestano** [comment]
Hi @tsjfd,

end revision expects the commit id, in case of git it is a 40 position [SHA1 hash](https://blog.thoughtram.io/git/2014/11/18/the-anatomy-of-a-git-commit.html#introducing-sha-1), can you try using he hash?

**Comment by tsjfd** [comment]
Thx!
